[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"  # ត្រូវតែតូចទាំងអស់

[[scheduled_functions]]
  name = "check-expirations"
  path = "/.netlify/functions/check-expirations"
  cron = "0 8 * * *"  # ឬ "*/10 * * * *" សម្រាប់សាកល្បងរាល់ 10 នាទី