[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[[functions]]
  from = "netlify/functions/check-expirations.js"
  to = "check-expirations"

[[scheduled_functions]]
  from = "netlify/functions/check-expirations.js"
  to = "check-expirations"
  cron = "0 8 * * *"